---

- name: Create VM on PVE
  proxmox_vm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password ]]"
    api_host: "{{ proxmox.api_host }}"
    node: "{{ item.value.node }}"
    name: "{{ item.key }}"
    cores: "{{ item.value.cores | default(proxmox_vm_defaults.cores) }}"
    memory: "{{ item.value.memory | default(proxmox_vm_defaults.memory) }}"
    balloon: "{{ item.value.balloon | default(proxmox_vm_defaults.balloon }}"
    scsihw: "{{ item.value.scsihw | default (proxmox_vm_defaults.scsihw) }}"
    net: "{{ item.value.net | default(proxmox_vm_defaults.net }}"
    vga: "{{ item.value.vga | default(proxmox_vm_defaults.vga) }}"
    ostype: "{{ item.value.ostype | default (proxmox_vm_defaults.ostype) }}"
    onboot: "{{ item.onboot | default(proxmox_vm_defaults.onboot) }}"
  with_dict: "{{ vms }}"
  loop_control:
    pause: 10
  register: created_proxmox_vm
  
- name: Add SCSI storage if specified
  proxmox_vm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password ]]"
    api_host: "{{ proxmox.api_host }}"
    node: "{{ item.value.node }}"
    name: "{{ item.key }}"
    scsi: "{{ item.value.scsi | default (proxmox_vm_defaults.scsi) }}"
  when: item.value.storage is scsi

- name: Add Virtio storage if specified
  proxmox_vm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password ]]"
    api_host: "{{ proxmox.api_host }}"
    node: "{{ item.value.node }}"
    name: "{{ item.key }}"
    virtio: "{{ item.value.virtio | default(proxmox_vm_defaults.virtio) }}"
  when: item.value.storage is virtio
